# Name of your application. Used to uniquely configure containers.
service: gwirian

# Name of the container image.
image: frocher/gwirian

# Paths
asset_path: /rails/public/assets
hooks_path: <%= File.join(Gem::Specification.find_by_name("gwirian-saas").gem_dir, ".kamal", "hooks") %>
secrets_path: <%= File.join(Gem::Specification.find_by_name("gwirian-saas").gem_dir, ".kamal/secrets") %>


# Deploy to these servers.
servers:
  web:
    - gwirian-prod
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# How you connect to your server
ssh:
  user: root  # If you use a different username to SSH to your server, specify it here

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
proxy:
  ssl: true
  host: app.gwirian.com

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: frocher

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - SENTRY_DSN
    - SIGNUP_NOTIFY_EMAIL
    - SMTP_USERNAME
    - SMTP_PASSWORD
  clear:
    RAILS_ENV: production
    BASE_URL: https://app.gwirian.com
    MAILER_FROM_ADDRESS: support@gwirian.com
    SMTP_HOST: smtp.postmarkapp.com
    SMTP_PORT: 587
    SOLID_QUEUE_IN_PUMA: true

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
  reindex: app exec --interactive --reuse "bin/rails elasticsearch:reindex"


# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "gwirian_storage:/rails/storage"


# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: arm64
  dockerfile: <%= File.join(Gem::Specification.find_by_name("gwirian-saas").gem_dir, "Dockerfile") %>


accessories:
  search:
    image: elastic/elasticsearch:8.19.9
    host: gwirian-prod
    env:
      clear:
        discovery.type: single-node
        xpack.security.enabled: false
        # Add memory limits to prevent OOM kills
        ES_JAVA_OPTS: "-Xms1g -Xmx1g"
