<%
  config_path = if Gwirian.saas?
    gem_path = Rails.root.join("saas").to_s
    File.join(gem_path, "config", "database.yml")
  else
    File.join("config", "database.sqlite.yml")
  end
%>
<%= ERB.new(File.read(config_path)).result %>
